### ISSUE TITLE
Trying to Get RMD File Name 

### ISSUE THREAD

**Issue by markgsheppard** [MullinsLab/r-scriptName#4]
I've tried the code in the documentation but I am not getting back the file name.

```r
filename <- current_cli_filename()
print(filename)
```
I am getting NULL. How would I augment the code to produce the file name?

**Comment by tsibley** [comment]
Hi @markgsheppard,

I'm not sure how you're rendering your RMarkdown document (e.g. from the command-line, from within RStudio, from another R program, etc.) or the context of your example in that document, but those will determine if there's a filename to get (there might not be!) and, if so, what it is (e.g. it might not be what you expect).

Per this package's documentation (emphasis added):

> `current_filename()` returns the result of `current_source_filename()` if not NULL, otherwise the result of `current_cli_filename()`, which might be NULL.  **You should use this wrapper function rather than the more-specific functions unless you have a very specific need.**

So try using the `current_filename()` function instead of the `current_cli_filename()` function. The latter won't work if the code is being `source()`d instead of run with `Rscript`.

**Comment by tsibley** [comment]
Closing this issue as I suspect there's no bug here, but we can still keep troubleshooting here.

**Comment by markgsheppard** [comment]
Hey @tsibley!
Ok so I ended up using:
```r
filename <-gsub(".*/","",documentPath()) # Extracts filename 
filename
``` 
within a Rmd code block and it returns the file name with the extension, but without the prior path.
