### ISSUE TITLE
Get full path

### ISSUE THREAD

**Issue by benjaminrich** [MullinsLab/r-scriptName#5]
Thanks for creating this useful package. It would be nice to be able to get the full path of the running scripts as an option, instead of just the file name.

**Comment by tsibley** [comment]
The script path is returned as-is, so whether its just a file name, a relative path, or an absolute path depends entirely on how `R`, `RScript`, or `source()` was invoked. All are possible. From the docs:

> No manipulation is done to the filename, so it may be relative or absolute.

I understand why having the full path is useful, but it's not trivial (and probably not possible) for this package to resolve a bare file name or other relative path correctly. The reason is that there could be `setwd()` calls between the script's invocation and the call to this package, and this package would have no way of knowing about those `setwd()` calls. There's no way, AFAIK, to get the working directory as it was at process start nor for a stack frame. Both of those would be required for this package to correctly resolve a relative path.

So this package returns the path as-is and leaves it to the caller (you :-) to know more about what `setwd()` have happened, if any. If you know there aren't any, then you can call [`normalizePath()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/normalizePath) on this package's return value get the absolute path.

**Comment by benjaminrich** [comment]
Thanks for the explanation. It makes sense.
